### PR TITLE
Add support for python 3 and scapy 2.5.0

### LINKED ISSUE #17: Exception when sending DHCP discover packet
On current Kali, it fails sending the DHCP discover packet.

```
root@kali:~# dhcpig eth0
[ -- ] [INFO] - using interface eth0
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/bin/dhcpig", line 516, in run
    sendPacket(dhcp_discover)
  File "/usr/bin/dhcpig", line 413, in sendPacket
    sendp(pkt, iface=conf.iface)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 315, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 42, in send
    sx = raw(x)
  File "/usr/lib/python2.7/dist-packages/scapy/compat.py", line 72, in raw
    return x.__bytes__()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/dhcp.py", line 269, in i2m
    lval = [f.addfield(pkt,b"",f.any2i(pkt,val)) for val in lval]
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 841, in addfield
    s = self.field.addfield(pkt, s, v)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
error: cannot convert argument to integer

[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 1
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 2
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 3
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 4
[ ?? ] 		waiting for first DHCP Server response
^C[ -- ]  -----  ABORT ...  -----
[DBG ] Waiting for Thread 0 to die ...
[DBG ] Waiting for Thread 1 to die ...
```

Scapy version: 2.4.0

### PR DESCRIPTION
**Pull request by charles2910**
Hi, I'm packaging dhcpig (mostly Q&A) for the new debian release and I've found some problems. Basically it wasn't working with newer scapy versions.

I've also had some help from Philippe (who ported it to python 3) and maniaque (who fixed some problems).

I did test it in my network and it seems to be working (it exausthed my dhcp server offerings). But I think more testing is needed to assure everything is working.

Oh, this fixes #17.

### CODE REVIEW

**Comment by charles2910** [comment]
Hi, there is also a [manpage](https://salsa.debian.org/pkg-security-team/dhcpig/-/blob/debian/master/debian/dhcpig.1) created by the former maintainer. Would you be interested in merging upstream?

**Comment by q2dg** [comment]
I wouldn't wait to merge anything here...this project is abandoned.
I encourage you to forget this repository and create a new one of your own.
Thanks!

**Comment by kamorin** [comment]
thank you q2dg for your honest criticism, the project has not been active - however, that is changing now.

I'll take a look at the PR, and get it merged asap.

**Review by kamorin — APPROVED** [review]
LGTM

**Comment by dlaporte** [comment]
I don’t know, q2dg has a point…

—
David LaPorte
***@***.***
________________________________

**Comment by kamorin** [comment]
also added the man page you referenced.

**Comment by charles2910** [comment]
Thanks, @kamorin. Nice to know this project is active!

**Pull request merged**
