### PR TITLE
a few subtle enhancements (win32 ready + RandMAC())

### PR DESCRIPTION
**Pull request by sgeto**
Hey,

Please review this PR. 
With the recent changes of scapy, this script can now also run on win32 with just a few, modifications. If you're fine with the changes I would also adjust the Readme.

I also replaced randomMAC() with RandMAC() just for fun.

### CODE REVIEW

**Comment by w1nst0nwU** [comment]
it would work on win64 or how to

**Comment by sgeto** [comment]
you need the latest dev version. then open scapy and type `get_windows_if_list()`.
Look for your interfaces name under `name` and use that as the interface argument when you run pig.py

example:

python pig.py -ct 5 "Qualcomm Atheros AR9285 Wireless Network Adapter"

**Comment by sgeto** [comment]
you need the latest dev version. then open scapy and type `get_windows_if_list()`.
Look for your interfaces name under `name` and use that as the interface argument when you run pig.py

example:

python pig.py -ct 5 "Qualcomm Atheros AR9285 Wireless Network Adapter"

**Comment by w1nst0nwU** [comment]
hi,@sgeto 
thank you for your reply. i want to ask if it could work on windows x86_64

**Comment by sgeto** [comment]
yes it does

**Comment by kamorin** [comment]
@sgeto what do you think of using os.name for windows identification?

>>> import os
>>> print os.name
posix

http://stackoverflow.com/questions/1325581/how-do-i-check-if-im-running-on-windows-in-python

also in your PR can you old randomMAC() code?

**Comment by sgeto** [comment]
Hey
no problem. I went back to randomMAC(). It was just my personal preference.

I tried a few combinations to set the interface and this seems to be the most straight-forward way. The thing is that there are a few abstractions necessary (no dnet and wpcap instead of pcap) to get it to work. Those are luckily internally handled in scapy.
So we would only want another OS check if the one done by scapy wouldn't suffice or if we need to know things like architecture, windows version etc. or if my test is somehow interfering with the rest of the script. I don't think we do.
I also think that choosing the device name/device description as the interface name is  easier than picking the so-called transport name on windows. The device name/device description can be queried from within windows with a simple `ipconfig /all`

**Pull request merged**
